﻿// This file was auto-generated by ML.NET Model Builder. 

 using Microsoft.ML;

 namespace Mmc.Blog.MLModel.Comment
{
    public partial class ToxiCommentFilter
    {
        public static ITransformer RetrainPipeline(MLContext context, IDataView trainData)
        {
            var pipeline = BuildPipeline(context);
            var model = pipeline.Fit(trainData);

            return model;
        }

        /// <summary>
        /// build the pipeline that is used from model builder. Use this function to retrain model.
        /// </summary>
        /// <param name="mlContext"></param>
        /// <returns></returns>
        public static IEstimator<ITransformer> BuildPipeline(MLContext mlContext)
        {
            // Data process configuration with pipeline data transformations
            var pipeline = mlContext.Transforms.Text.FeaturizeText(@"comment_text", @"comment_text")      
                                    .Append(mlContext.Transforms.Concatenate(@"Features", @"comment_text"))      
                                    .Append(mlContext.Transforms.Conversion.MapValueToKey(@"target", @"target"))      
                                    .Append(mlContext.Transforms.NormalizeMinMax(@"Features", @"Features"))      
                                    .Append(mlContext.MulticlassClassification.Trainers.LbfgsMaximumEntropy(l1Regularization:1.68970536461624F,l2Regularization:0.416515938555551F,labelColumnName:@"target",featureColumnName:@"Features"))      
                                    .Append(mlContext.Transforms.Conversion.MapKeyToValue(@"PredictedLabel", @"PredictedLabel"));

            return pipeline;
        }
    }
}
