// <auto-generated />
using System;
using Microsoft.EntityFrameworkCore;
using Microsoft.EntityFrameworkCore.Infrastructure;
using Microsoft.EntityFrameworkCore.Migrations;
using Microsoft.EntityFrameworkCore.Storage.ValueConversion;
using Mmc.Data;

#nullable disable

namespace Mmc.Data.Migrations
{
    [DbContext(typeof(BaseDbContext))]
    [Migration("20220314004408_Initial")]
    partial class Initial
    {
        protected override void BuildTargetModel(ModelBuilder modelBuilder)
        {
#pragma warning disable 612, 618
            modelBuilder
                .HasAnnotation("ProductVersion", "6.0.0")
                .HasAnnotation("Relational:MaxIdentifierLength", 64);

            modelBuilder.Entity("Mmc.Core.Entity.BlogMaster", b =>
                {
                    b.Property<int>("BlogMasterId")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("int")
                        .HasColumnName("blog_master_id");

                    b.Property<long>("BlogMasterAuthorAdminId")
                        .HasColumnType("bigint")
                        .HasColumnName("blog_master_author_id");

                    b.Property<string>("BlogMasterAuthorName")
                        .IsRequired()
                        .HasColumnType("longtext")
                        .HasColumnName("blog_master_author_name");

                    b.Property<string>("BlogMasterBody")
                        .IsRequired()
                        .HasColumnType("longtext")
                        .HasColumnName("blog_master_body");

                    b.Property<DateTime>("BlogMasterPostedDate")
                        .HasColumnType("datetime(6)")
                        .HasColumnName("blog_master_posted_date");

                    b.Property<string>("BlogMasterTitle")
                        .IsRequired()
                        .HasMaxLength(40)
                        .HasColumnType("varchar(40)")
                        .HasColumnName("blog_master_title");

                    b.HasKey("BlogMasterId");

                    b.HasIndex("BlogMasterAuthorAdminId");

                    b.ToTable("blog_master", (string)null);
                });

            modelBuilder.Entity("Mmc.Core.Entity.NoticeMaster", b =>
                {
                    b.Property<long>("NoticeMasterId")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("bigint")
                        .HasColumnName("notice_master_id");

                    b.Property<long>("NoticeMasterAuthorUserMasterId")
                        .HasColumnType("bigint");

                    b.Property<string>("NoticeMasterBody")
                        .HasColumnType("longtext")
                        .HasColumnName("notice_master_body");

                    b.Property<string>("NoticeMasterNoticePicture")
                        .HasColumnType("longtext")
                        .HasColumnName("notice_master_picture");

                    b.Property<string>("NoticeMasterTitle")
                        .IsRequired()
                        .HasColumnType("longtext")
                        .HasColumnName("notice_master_title");

                    b.HasKey("NoticeMasterId");

                    b.HasIndex("NoticeMasterAuthorUserMasterId");

                    b.ToTable("notice_master", (string)null);
                });

            modelBuilder.Entity("Mmc.Core.Entity.UserCredentials", b =>
                {
                    b.Property<int>("UserCredentialsId")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("int")
                        .HasColumnName("user_credentials_id");

                    b.Property<string>("UserCredentialsEmail")
                        .IsRequired()
                        .HasColumnType("longtext")
                        .HasColumnName("user_credentials_email");

                    b.Property<string>("UserCredentialsPassword")
                        .IsRequired()
                        .HasColumnType("longtext")
                        .HasColumnName("user_credentials_password");

                    b.Property<long>("UserCredentialsUserId")
                        .HasColumnType("bigint");

                    b.HasKey("UserCredentialsId");

                    b.HasIndex("UserCredentialsUserId")
                        .IsUnique();

                    b.ToTable("User_Credentials", (string)null);
                });

            modelBuilder.Entity("Mmc.Core.Entity.UserMaster", b =>
                {
                    b.Property<long>("UserMasterId")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("bigint")
                        .HasColumnName("user_id");

                    b.Property<int>("UserMasterCredentialId")
                        .HasColumnType("int")
                        .HasColumnName("user_credentials");

                    b.Property<string>("UserMasterName")
                        .IsRequired()
                        .HasColumnType("longtext")
                        .HasColumnName("user_name");

                    b.HasKey("UserMasterId");

                    b.ToTable("User_Master", (string)null);
                });

            modelBuilder.Entity("Mmc.Core.Entity.BlogMaster", b =>
                {
                    b.HasOne("Mmc.Core.Entity.UserMaster", "BlogMasterAuthorAdmin")
                        .WithMany("Blogs")
                        .HasForeignKey("BlogMasterAuthorAdminId")
                        .OnDelete(DeleteBehavior.Cascade)
                        .IsRequired();

                    b.Navigation("BlogMasterAuthorAdmin");
                });

            modelBuilder.Entity("Mmc.Core.Entity.NoticeMaster", b =>
                {
                    b.HasOne("Mmc.Core.Entity.UserMaster", "NoticeMasterAuthor")
                        .WithMany("Notices")
                        .HasForeignKey("NoticeMasterAuthorUserMasterId")
                        .OnDelete(DeleteBehavior.Cascade)
                        .IsRequired();

                    b.Navigation("NoticeMasterAuthor");
                });

            modelBuilder.Entity("Mmc.Core.Entity.UserCredentials", b =>
                {
                    b.HasOne("Mmc.Core.Entity.UserMaster", "UserCredentialsUser")
                        .WithOne("UserMasterCredential")
                        .HasForeignKey("Mmc.Core.Entity.UserCredentials", "UserCredentialsUserId")
                        .OnDelete(DeleteBehavior.Cascade)
                        .IsRequired();

                    b.Navigation("UserCredentialsUser");
                });

            modelBuilder.Entity("Mmc.Core.Entity.UserMaster", b =>
                {
                    b.Navigation("Blogs");

                    b.Navigation("Notices");

                    b.Navigation("UserMasterCredential")
                        .IsRequired();
                });
#pragma warning restore 612, 618
        }
    }
}
